name: Test

env:
  CI: true
  DEBUG: pw:api
  TZ: Asia/Ho_Chi_Minh
  BASE_URL: ${{ secrets.BASE_URL }}
  GWT_GOLFY_DEFAULT_PASSWORD: ${{ secrets.GWT_GOLFY_DEFAULT_PASSWORD }}
  GWT_GOLFY_STARTER_USERNAME: ${{ secrets.GWT_GOLFY_STARTER_USERNAME }}
  AUTH_USERNAME: ${{ secrets.GWT_GOLFY_STARTER_USERNAME }}
  AUTH_PASSWORD: ${{ secrets.GWT_GOLFY_DEFAULT_PASSWORD }}

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: false
        default: 'main'

jobs:
  run:
    strategy:
      matrix:
        node: ['20', '22.5.1']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ github.event.inputs.branch }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: install Playwright
        run: npx playwright install --with-deps > /dev/null
      - name: run features
        run: npm run test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-report-${{ matrix.node }}
          path: reports/report.html

  dependabot:
    name: 'Dependabot'
    needs: [run]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
